### ISSUE TITLE
Remove hacked GraphQL.Server.Transports.AspNetCore middleware

### ISSUE THREAD

**Issue by floyd-may** [asemio/otto-the-geek#20]
As a fix for #19, we included a hacked middleware copied from `GraphQL.Server.Transports.AspNetCore`. When they rev their version (v3.4.0 currently) to include async support, we can remove our hack and use their middleware again.

Related issue: https://github.com/graphql-dotnet/server/issues/297

**Comment by sungam3r** [comment]
@floyd-may middleware you copied from `GraphQL.Server.Transports.AspNetCore` was rewritten completely to support custom deserializers and advanced cases.

**Comment by floyd-may** [comment]
For posterity, version 3.x wasn't available on NuGet in April ;)

**Comment by sungam3r** [comment]
![изображение](https://user-images.githubusercontent.com/21261007/103369401-14ab5c80-4adb-11eb-82e5-a51a2b83289c.png)

**Comment by floyd-may** [comment]
@sungam3r please stop. The 4.x rev of this package didn't exist on NuGet until 3 months ago, long after I created the workaround:

https://www.nuget.org/packages/GraphQL.Server.Transports.AspNetCore

**OttoTheGeek will not take a dependency on a develop version or on a version that's not published on NuGet**.

We are currently working on updating our dependencies to later versions of the GraphQL package, but that doesn't come for free. There are breaking changes that we have to deal with.

**Comment by sungam3r** [comment]
> The 4.x rev of this package didn't exist on NuGet until 3 months ago

Уes. I am only showing by this that the following statement was answered:

> When they rev their version (v3.4.0 currently) to include async support, we can remove our hack and use their middleware again.



_
> OttoTheGeek will not take a dependency on a develop version or on a version that's not published on NuGet.

OK. Any v4.x.x is not a develop version and is published on NuGet. In general, all my comments are for informational purposes only. I received a email notification and decided to answer.

**Comment by floyd-may** [comment]
Fixed in v1.0.1.
