### ISSUE TITLE
Handle lists of scalars

### ISSUE THREAD

**Issue by floyd-may** [asemio/otto-the-geek#34]
Currently Otto can't handle lists of scalars. There's an underlying issue in GraphQL-Net that causes problems.

**Comment by sungam3r** [comment]
@floyd-may What issue are you talking about?

**Comment by floyd-may** [comment]
@sungam3r an NRE in GraphTypesLookup. That file has been altered significantly, so I'm going to retest when we've upgraded to 3.x of the core lib.

**Comment by sungam3r** [comment]
Was this NRE documented in some issue?

**Comment by floyd-may** [comment]
No. Seemed pointless since we're already working to upgrade (hence the labeling). If the issue persists in v3.x I'll file an issue.
